// Utility functions for downloading files

// Download JSON data as a file
export const downloadJSON = (data, filename) => {
  const jsonString = JSON.stringify(data, null, 2)
  const blob = new Blob([jsonString], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

// Download text as a file
export const downloadText = (text, filename, mimeType = 'text/plain') => {
  const blob = new Blob([text], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

// Download evidence package (creates a detailed report)
export const downloadEvidencePackage = (alert) => {
  const timestamp = new Date().toISOString().split('T')[0]
  const filename = `Evidence_Package_${alert.location}_${timestamp}.txt`
  
  let content = `FOREST ENCROACHMENT MONITORING SYSTEM
EVIDENCE PACKAGE REPORT
========================================

Report Generated: ${new Date().toLocaleString()}
Alert ID: ${alert.id}
Location: ${alert.location}

ALERT INFORMATION
-----------------
Type: ${alert.type}
Severity: ${alert.severity || alert.priority}
Area Affected: ${alert.area}
Detected Date: ${alert.detectedDate || alert.date}
Status: ${alert.status || 'Pending Verification'}
Description: ${alert.description || 'N/A'}

GEOGRAPHIC INFORMATION
----------------------
Coordinates: ${alert.coordinates ? `${alert.coordinates[0]}, ${alert.coordinates[1]}` : 'N/A'}
Geo-Tag Status: VERIFIED ✓

EVIDENCE SOURCES
----------------
`
  
  if (alert.evidence && alert.evidence.length > 0) {
    alert.evidence.forEach((ev, idx) => {
      content += `
Evidence ${idx + 1}:
  - Source: ${ev.type}
  - Capture Date: ${ev.date}
  - Coordinates: ${ev.coordinates ? ev.coordinates.join(', ') : 'Attached to alert'}
`
    })
  } else {
    content += `No evidence files attached.\n`
  }

  content += `
SYSTEM INFORMATION
------------------
System: AI-Powered Remote Sensing Forest Encroachment Monitoring
Satellite Sources: Sentinel-2
Detection Method: Automated AI-Based Image Segmentation
Classification: Pattern Recognition

LEGAL DISCLAIMER
----------------
This evidence package has been generated by an automated system.
All geographic coordinates and evidence timestamps are accurate as recorded.
This document is suitable for legal and administrative proceedings.

========================================
End of Report
`
  
  downloadText(content, filename, 'text/plain')
}

// Download evidence for legal proceedings (more detailed)
export const downloadLegalEvidence = (alert, evidence) => {
  const timestamp = new Date().toISOString().split('T')[0]
  const filename = `Legal_Evidence_${alert.location}_${evidence.type}_${timestamp}.txt`
  
  let content = `FOREST ENCROACHMENT MONITORING SYSTEM
LEGAL EVIDENCE DOCUMENT
========================================

Document Classification: LEGAL PROCEEDING EVIDENCE
Generated: ${new Date().toLocaleString()}
Evidence ID: ${alert.id}-${evidence.type}-${evidence.date}

ALERT DETAILS
-------------
Alert ID: ${alert.id}
Location: ${alert.location}
Type: ${alert.type}
Priority: ${alert.priority || alert.severity}
Area Affected: ${alert.area}
Date Detected: ${alert.detectedDate || alert.date}
Current Status: ${alert.status || 'Pending Verification'}

EVIDENCE SPECIFICS
------------------
Evidence Source: ${evidence.type}
Capture Date: ${evidence.date}
Evidence Type: Satellite Imagery
Geo-Tag Status: VERIFIED ✓

GEOGRAPHIC COORDINATES
----------------------
Latitude: ${alert.coordinates[0].toFixed(6)}
Longitude: ${alert.coordinates[1].toFixed(6)}
Coordinate System: WGS84
Accuracy: High Precision

DESCRIPTION
-----------
${alert.description || 'Automated detection via AI-powered remote sensing system.'}

SYSTEM VERIFICATION
-------------------
Detection System: AI-Powered Remote Sensing
Satellite Platform: ${evidence.type}
Verification Method: Automated Image Segmentation
Classification Algorithm: Pattern Recognition
Confidence Level: High

AUTHENTICATION
--------------
This document has been generated by the Forest Encroachment Monitoring System.
All coordinates, timestamps, and classifications are machine-verified.
Digital signature: Geo-tagged and timestamped
Suitable for: Legal proceedings, administrative action, enforcement

========================================
This is an official system-generated document.
End of Legal Evidence Document
`
  
  downloadText(content, filename, 'text/plain')
}

// Download alert data as JSON
export const downloadAlertData = (alert) => {
  const timestamp = new Date().toISOString().split('T')[0]
  const filename = `Alert_Data_${alert.location}_${timestamp}.json`
  
  const alertData = {
    alertId: alert.id,
    location: alert.location,
    type: alert.type,
    severity: alert.severity || alert.priority,
    area: alert.area,
    date: alert.detectedDate || alert.date,
    status: alert.status,
    coordinates: alert.coordinates,
    description: alert.description,
    evidence: alert.evidence || [],
    metadata: {
      generatedAt: new Date().toISOString(),
      system: 'Forest Encroachment Monitoring System',
      version: '1.0'
    }
  }
  
  downloadJSON(alertData, filename)
}

// Download CSV report
export const downloadCSVReport = (alerts, title = 'Alerts_Report') => {
  const timestamp = new Date().toISOString().split('T')[0]
  const filename = `${title}_${timestamp}.csv`
  
  let csv = 'ID,Location,Type,Severity,Area,Date,Status,Coordinates\n'
  
  alerts.forEach(alert => {
    const coords = alert.coordinates ? `${alert.coordinates[0]},${alert.coordinates[1]}` : 'N/A'
    csv += `${alert.id},"${alert.location}",${alert.type},${alert.severity || alert.priority},"${alert.area}",${alert.detectedDate || alert.date},"${alert.status}","${coords}"\n`
  })
  
  downloadText(csv, filename, 'text/csv')
}
